[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "<"
key = "§"

[[keyboard.bindings]]
chars = ">"
key = "°"
mods = "Shift"

[[keyboard.bindings]]
chars = "{"
key = "7"
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = "0"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = "§"
mods = "Alt"

[[keyboard.bindings]]
chars = "\\"
key = "+"
mods = "Alt"

#
# [[keyboard.bindings]]
# chars = "{"
# key = 28
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "}"
# key = 25
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "@"
# key = 37
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = '\'
# key = 26
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "|"
# key = 26
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "~"
# key = 45
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "["
# key = 23
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "]"
# key = 22
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "'"
# key = 24
# mods = "Alt"
#
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = 36
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

# [mouse.url.launcher]
# program = "open"

[scrolling]
history = 10000

[window]
decorations = "Buttonless"
dynamic_padding = false
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 2
y = 2

[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
