[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "<C-t>"
run  = "plugin --sync hide-preview"
desc = "Hide or show preview"
