[manager]
show_hidden = true
show_symlink = true

[preview]
image_filter = "catmull-rom"
sixel_fraction = "10"
image_quality = 90
ueberzug_scale = 1.0
max_width = 4096
max_height = 4096

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
