[manager]
ratio = [2, 4, 3]
sort_by = "natural"
sort_sensitive = false
show_hidden = true
show_symlink = true

[preview]
image_delay = 100
image_filter = "lanczos3"
image_quality = 90
sixel_fraction = 10
ueberzug_scale = 1.0
max_width = 4096
max_height = 4096

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
